name       : dep
version    : 0.5.0
release    : 1
source     :
    # Build script expects to be in a valid git repository
    - git|https://github.com/golang/dep.git : v0.5.0
license    : BSD-3-Clause
component  : programming.tools
summary    : Go dependency management tool
description: |
    dep is a dependency management tool for Go.
replaces   :
    - godep
builddeps  :
    - golang
setup      : |
    mkdir -p $(go env GOPATH)/src/github.com/golang
    mv $workdir $(go env GOPATH)/src/github.com/golang/dep
build      : |
    cd $(go env GOPATH)/src/github.com/golang/dep
    %make build
install    : |
    cd $(go env GOPATH)/src/github.com/golang/dep
    install -Dm00755 ./dep $installdir/usr/bin/dep
#check      : |
#    cd $(go env GOPATH)/src/github.com/golang/dep
#    %make test
# Test are really slow, give a lot of connection timeouts and require networking.
